### ISSUE TITLE
Expansion proof viewer: divider in wrong position

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#536] opened 2016-06-22 11:22 UTC
On the CLI, enter
```
prooftool( LinearExampleProof( 12 ))
```
Then click View->View expansion proof. This results in a new window where only the succedent is displayed. The area for the antecedent apparently has width 0. This should be of noticeable width.

**Comment by gebner** [comment] 2016-06-22 11:47
Interestingly enough, this only happens if you open the expansion sequent viewer from the menu in the LK viewer, not if you call prooftool on the expansion proof.

**Comment by gebner** [comment] 2016-06-26 14:57
The divider is also put in a different place if you change the font size.  When starting from the CLI, the divider is on the left side; when resizing, the divider is suddenly in the middle.

Part of the problem is that the expansion proof viewer is currently wrapped in a scroll panel (unnecessary, as the antecedent and succedent panels are already scrollable), and the whole viewer (including divider) is regenerated every time the font size changes.  We would not need any workaround, if we just dropped the scrollpane, set the correct `preferredSize` on the DrawExpansionTree panels, and let Swing do the layout for us.

**Comment by gebner** [comment] 2016-06-29 10:43
AFAICT, this behavior has existed for a long time and would require a larger refactoring to fix.  Hence rescheduling for gapt 2.3.

**Comment by loewenheim** [comment] 2016-06-29 12:45
I remember thinking, during my last refactoring of prooftool, that at least one of the various panes nested inside each other had to be superfluous, but I couldn't figure out which. Do you think that the ScrollPane should be axed altogether?

**Comment by gebner** [comment] 2016-06-29 13:24
> Do you think that the ScrollPane should be axed altogether?

No, I'm pretty sure we need it for the SequentProofViewer/LKProofViewer/StructViewer/etc., these just provide a large panel and don't do scrolling themselves.  IMHO it should just be separated into a separate subclass of ProofToolViewer that wraps everything in a scroll pane.

**Comment by loewenheim** [comment] 2016-06-29 13:26
So we make a subclass of ProofToolViewer that supports scrolling, and e.g. SequentProofViewer would extend it, but ExpansionSequentViewer wouldn't?

**Comment by gebner** [comment] 2016-06-29 13:39
Yeah, I think that's the best idea.

**Comment by gebner** [comment] 2016-07-14 06:30
Fixed with the merge of the `prooftool-wip` branch.

**Closed by gebner** 2016-07-14 06:30 UTC
Labels: Bug
