### ISSUE TITLE
Cut-elimination does not eliminate all cuts

### ISSUE THREAD

**Issue by Lettmann** [gapt/gapt#714] opened 2018-08-09 12:47 UTC
When running the following commands in gapt, you get a proof with cuts.

import examples.ExponentialCompression._
val proof = instantiateProof.Instantiate( le"omega (s (s 0))" )
val cutFree = cutNormal(proof)

**Comment by jannikvierling** [comment] 2018-08-09 13:42
The issue is now fixed in `master`. The call `cutNormal(proof)` returns a cut free proof, however it takes +20 minutes to compute this proof. You can run `cutNormal(proof, false)` which does not clean structural rules during cut elimination and computes the cut free proof in approximately 8 minutes.

**Closed by jannikvierling** 2018-08-09 13:42 UTC

**Comment by gebner** [comment] 2018-08-09 14:31
Just fyi, the proof term-based cut-elimination algorithm as described in [1] computes a cut-normal form in about a second:
```scala
val cutFree = normalizeLKt.lk( proof )
// 1123 ms
```

[1] G. E., Fast cut-elimination using proof terms: an empirical study, CL&C'18. [preprint](https://gebner.org/pdfs/2018-03-16_fastlkt.pdf)

**Comment by Lettmann** [comment] 2018-08-14 09:10
Werde ich sofort zitieren und verwenden :) Wenn ich es richtig sehe, ist es aber nur bei arXiv online, richtig?

**Comment by gebner** [comment] 2018-08-14 09:40
It will be published as part of the workshop proceedings in EPTCS, but that may still take a few more weeks.
