### ISSUE TITLE
CutIntroduction does not produce minimal proofs

### ISSUE THREAD

**Issue by DarwinsBuddy** [gapt/gapt#285] opened 2015-02-06 17:46 UTC
While I tried to extract the extended Herbrand Sequent of a LinearExampleProof I observed that our cutIntro algorithms all do not return the minimal proof, with 1 cut introduced.
As we know for now, many_cuts_one_quantifier (i.e. the maxsat algorithm) is known to find _a_ minimal _grammar_ but still cannot distinguish between the _proofs_ of different sizes with underlying minimal grammars. So the minimal proof is not guaranteed to be found.
In contrast one_cut_one_quantifier and one_cut_many_quantifiers should return the minimal one, but return following in case of LinearExampleProof(8):
![notminimal](https://cloud.githubusercontent.com/assets/490836/6084292/f6779196-ae2f-11e4-81dd-77f9d19dfe54.png)
Months ago I extracted following proof from the prooftool for my thesis (again LinearExampleProof(8)), which obviously is the minimal one
![minimal](https://cloud.githubusercontent.com/assets/490836/6084293/f67a1d12-ae2f-11e4-82a3-ca252d6f10e0.png)

**Comment by DarwinsBuddy** [comment] 2015-02-06 18:24
I again reviewed the behaviour of my commit [23de89ddb297ca12ee005c7c59c04235122dc698](https://github.com/gapt/gapt/commit/23de89ddb297ca12ee005c7c59c04235122dc698)
against the one before that. It seems that I unknowingly broke the canonical solution computation procedure. I will have a look on it on Mondays. I hope I can find the error soon.

**Comment by frehn** [comment] 2015-02-10 13:41
Hey Christoph,

thanks for spotting the bug and investigating it. Looking at the two proofs, it seems to me that they are induced by different grammars! So maybe the problem is in the choice of the grammar, and not in the computation of the solution.

To be more precise, the proof from your thesis has, on the right branch above the cut, 2 forall-left rules (hence it should be induced by a grammar U o S with |S|=2). On the other hand, the bigger proof has 4 forall-left inferences there, hence it is induced by a grammar U o S with |S|=4.

If I can be of further assistance with squashing this bug, just let me know.

**Comment by frehn** [comment] 2015-02-10 13:44
One more comment: I could be wrong, but I think both proofs are fine: one corresponds to a "2x4"-grammar, the other to a "4x2" grammar. In both cases, the grammar has "size" 2+4=4+2=6. I don't remember exactly how we choose grammars/solutions/proof, but depending on our choice, this might not be a bug, but rather a "don't care" non-deterministic effect.

**Comment by gisellemnr** [comment] 2015-02-10 13:47
The one_cut_one_quantifier algorithm explicitly tests all minimal grammars and chooses the one that generates the smallest proof (w.r.t. the number of inference rules). So in principle it should find the one from Christoph's thesis... I did not have time to look at the code yet to see what is going on though.

**Comment by DarwinsBuddy** [comment] 2015-02-10 14:00
Thanks Daniel for participating in solving this issue.
The proofs themselves are right, but as Giselle pointed out, the proofs are
not minimal.
In fact (as Giselle mentioned) the proof in my thesis should be found *at
least* by the one_one method. Since I commited my changes of the
computeCanonicalSolution method it shows this behaviour.
So I'm pretty sure it is orginiated somewhere in this changeset. I looked
through my changes and the previous implementation and couldn't find the
bug yet.

I would appreciate any help regarding this issue.
@Daniel: If you have time to meet and track down the bug together, you
would do me a huge favor.

2015-02-10 14:47 GMT+01:00 Giselle Reis <notifications@github.com>:

> The one_cut_one_quantifier algorithm explicitly tests all minimal grammars
> and chooses the one that generates the smallest proof (w.r.t. the number of
> inference rules). So in principle it should find the one from Christoph's
> thesis... I did not have time to look at the code yet to see what is going
> on though.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gapt/gapt/issues/285#issuecomment-73701091>.
>



-- 
Tel.: +43 676 643 00 55
EMail: christoph.spoerk@gmail.com

**Comment by frehn** [comment] 2015-02-10 14:10
@DarwinsBuddy: Sure, no problem - just contact me via email and we can make an appointment. Note that this week, I only have free time tomorrow (Feb 11), but we can also meet next week if this is bad for you.

**Comment by gisellemnr** [comment] 2015-02-10 20:31
I reverted Christoph's commit and reimplemented the generation of cut formulas in a simpler way (I think Christoph was confusing the cut-formulas with the implications from the extended herbrand sequent). The implementation and integration with the maxsat cut-intro method are in these two commits: 990ca5383f519aa9071d52ca11b3a465285a2199 and adf3af06fdc874979bd1dc7676fd1d8ffe42b1f4

I tested on the LinearExampleProof(18) and it does generate two cut-fomulas, but I could not check if they are correct because they are huge. If any of you know how to check if correct formulas are being generated, it would be good.

Additionally there is a third commit with the change to make the maxsat method return a proof in case it computes a simple grammar (2a653948e5f42e591ef329ad34c9083a1145b2cf). This should be nice for the next run of the cut-intro tests. 

The proofs with many cuts are still not generated, but this is another issue. If you are ok, I would close this one.

**Comment by frehn** [comment] 2015-02-11 09:47
I can confirm that Giselle's changes cause the first proof given in the original issue to be produced, as expected. Thanks Giselle!

From my point of view, it's fine to close this issue. Regarding the question of correctness of the cut-formulas - one way to test that would be to build the proof for n>1 cuts. I'll take a look at implementing this today.

**Comment by gisellemnr** [comment] 2015-02-11 09:59
Good, thank you Daniel!

**Closed by gisellemnr** 2015-02-11 09:59 UTC
Labels: Bug
