### ISSUE TITLE
layers mixed when introducing 2 cuts

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#310] opened 2015-03-23 10:40 UTC
In the current ncuts-branch, do the following in the CLI:

:load examples/ProofSequences.scala
val proof = LinearExampleProof(13)
val res = cutIntro.many_cuts_one_quantifier( proof, 2 )
prooftool( res )

This results in:

java.lang.Exception: toString: expression is not FOL: s:(ι->ι)
  at at.logic.language.fol.FOLExpression$class.toString(fol.scala:53)
  at at.logic.language.fol.FOLLambdaConst.toString(base.scala:27)
  at at.logic.gui.prooftool.gui.DrawSequent$.parseNestedUnaryFunction(DrawSequent.scala:208)
  at at.logic.gui.prooftool.gui.DrawSequent$.formulaToLatexString(DrawSequent.scala:185)
  at at.logic.gui.prooftool.gui.DrawSequent$$anonfun$formulaToLatexString$6.apply(DrawSequent.scala:163)
  at at.logic.gui.prooftool.gui.DrawSequent$$anonfun$formulaToLatexString$6.apply(DrawSequent.scala:163)
  at scala.collection.immutable.List.map(List.scala:273)
  at at.logic.gui.prooftool.gui.DrawSequent$.formulaToLatexString(DrawSequent.scala:163)
  at at.logic.gui.prooftool.gui.DrawSequent$.formulaToLabel(DrawSequent.scala:78)
  at at.logic.gui.prooftool.gui.DrawSequent$$anon$1$$anonfun$8.apply(DrawSequent.scala:72)
...

Instead, the proof should be displayed.

@frehn I think we agreed that the cut-introduction code should be implemented using FOL-notions only (since it is very unlikely that we will ever introduce higher-order cut formulas ;-)

**Comment by frehn** [comment] 2015-03-23 10:58
Unfortunately (?) I cannot reproduce the error you describe - prooftool displays the proof correctly on my machine.

**Comment by shetzl** [comment] 2015-03-23 12:55
After removing and re-adding the branch, doing sbt clean and sbt assembly I cannot reproduce this anymore either. So I am closing this issue.

**Comment by shetzl** [comment] 2015-04-25 07:40
I am reopening this issue since the problem has reappeared in my local repository in the master branch. Doing sbt clean and sbt assembly does not help. It also happens with:
:load examples/ProofSequences.scala
val p = LinearExampleProof( 9 )
val q = cutIntro.one_cut_one_quantifier( p )
prooftool( q )

The exception is the same.

Can anybody else reproduce this?

**Comment by quicquid** [comment] 2015-04-26 17:54
@shetzl : I just confirmed the exception ( toString: expression is not FOL: s:(ι->ι) ).

**Comment by quicquid** [comment] 2015-04-26 17:59
Interestingly enough, using:

    val formulas = q.nodes.flatMap(_.vertex.asInstanceOf[Sequent].toFSequent.formulas)
    formulas.map(_.toString)

works without problems. Even ``formulas.map(_.asInstanceOf[FOLFormula].toString)``` is fine.

**Comment by gisellemnr** [comment] 2015-04-26 22:29
Hi, I bumped into this today... turns out there was a case missing in the toString method in fol. Commit 75286e9a50018818c2e57c875fc9eb97bf302908 fixes it, so I am closing it.

**Closed by gisellemnr** 2015-04-26 22:29 UTC
