### ISSUE TITLE
switchLogicalConstants throws exception when computing deep formula of expansion tree

### ISSUE THREAD

**Issue by shetzl** [gapt/gapt#292] opened 2015-02-11 16:56 UTC
Do the following in the CLI:
val p = loadProver9LKProof( "testing/TSTP/prover9/ALG/ALG014+1/Prover9---1109a.THM-Ref.s.out" ) // loading this proof takes a while
val E = extractExpansionSequent( p )
at.logic.calculi.expansionTrees.toDeep( E )

This results in an exception, thrown from switchLogicalConstants. The expected output is an FSequent, the deep sequent of E.

Interestingly, applying the above commands to the proof in ALG004-1 works well. Maybe one proof contains a constant which the other does not contain?

@frehn Daniel, I believe you know this code best, could you have a look at it?

**Comment by frehn** [comment] 2015-02-12 13:57
I have commited a hack that "fixes" this problem: 82184ae5225557be25ea9f1d00240e2e177725e5

Towards a "real" fix, let me summarize the problem as I see it.

In GAPT, we have "layers" for the different logics we support (Lambda Calculus, HOL, FOL, ...). Due to technical reasons, there are multiple classes implementing what is logically the same thing, namely the logical constants And, Or, Bottom etc, for the different layers. This causes the problem that an algorithm, implemented in the HOL layer, will by default introduce the HOL-constants when creating new syntactic objects. But, when the algorithm is called by another algorithm working on the FOL layer, we actually expect the formula to contain the FOL constants.

The solution to this problem is to have factories creating the syntactic objects, which take care of such situations by inserting the "appropriate" constants by looking at the context. Eg when we construct a formula \neg A, the factory inspects A and uses the \neg constant appropriate for A.

The bug in this issue is, roughly speaking, that when we construct a formula A \land B, where A is from the HOL layer and B is from the FOL layer, we simply use the left formula, A here, as the context, and therefore insert a HOL \land. We actually want a FOL \land.

There seem to be a number of possible "real" solutions to the problem. I mention two here as basis for a discussion:

* Find a way to have only one copy of each logical constant in the system. The problem should then simply disappear. This seems nice, but I don't know if it is possible.

* Add additional structure to the factories: In our current implementation, there exists a natural order on the factories induced by layer inclusion: Lambda < HOL < FOL < Schemata. Note that bigger layers "are aware of" the smaller layers. If we add such an order to the factories, then the solution to constructing A \land B above would be to take the factory max(A.factory, B.factory), where max refers to the order just discussed. This might be less nice, but seems consistent and easily implementable.

**Comment by quicquid** [comment] 2015-02-16 13:09
Hi Daniel and Stefan!

I didn't have too much time to think about it during the last days, but something strikes me as strange here. In my opinion, in an application (s t), the factories of s and t have to agree, otherwise this means mixing layers. There are some explicit conversions in folalgorithms (recreateWIthFactory, hol2folpure) in case we have different sources, but fixing this automatically in the constructor just hides the problem to me. 

Not having looked at the problem yet, my guess is that somewhere in the expansion tree extraction, explicit hol constants are used instead of using the factory (e.g. top and bottom in the case of weakening). All the original expressions come from the (FOL) proof, which has the same factory for all terms.

**Comment by frehn** [comment] 2015-02-16 13:27
Hi Martin,

the problem is not in the expansion trees, but in the constructor objects in HOL which sometimes create something "from nothing" (e.g. And.apply( fs: List[HOLFormula] ) in the case that fs = Nil). Assume that this And.apply function is used in some HOL-layer algorithm which is called from FOL. Then, in all instances where fs = Nil, the And method would not know to put the FOL-TopC there.

Removing functions of the And.apply(List) type to get better control seems bad to me, the interface these functions provide is just too natural. 

Another solution, which seems to be suggested by Martin above, is to remove the "switchLogicalConstants" method altogether, and to require explicit hol2fol calls whenever a HOL-layer-implementation is used in a FOL-context (e.g. Substitution/FOLSubstitution).

**Comment by quicquid** [comment] 2015-02-16 13:38
Hi Daniel,

I'm wondering, if this can be solved like the interface of some arlgotihms, where an additional implicit argument for the factory is used. The would change the signature of And.apply to (HOLExpression, HOLExpression)(FactoryA) => HOLExpression. Then the constructor can create the correct constant.

**Comment by frehn** [comment] 2015-02-16 13:41
This seems like a possibility, but it would seem to leak the factories into the interface of GAPT (note that every algorithm which uses And.apply then has to provide a value to the implicit argument explicitly at some point). I think this should definitely be avoided.

**Comment by quicquid** [comment] 2015-02-16 14:01
You are right with that - I just added the factories in a private branch, which creates troubles for expansion trees, which have no factory associated on their own. I guess the easy way out is to put the effort to the programmers by forcing the list to have at least one element (e.g. use the signature HOLExpression => List[HOLExpression] => HOLExpression). This doesn't solve the initial problem though.

**Comment by frehn** [comment] 2015-02-16 14:06
I think changing the signature/semantics of the And: List[HOLFormula] => HOLFormula method is not very nice as well since the current methiod just so nicely corresponds to the usual mathematical definition of \bigland:

\bigland_{i=1...n} F_i = \top for n=0
\bigland_{i=1...n} F_i = F_n \land \bigland_{i=1...n-1} F_i for n>0

**Comment by gisellemnr** [comment] 2015-02-16 14:13
What about Daniel's first suggestion?
"Find a way to have only one copy of each logical constant in the system.
The problem should then simply disappear. This seems nice, but I don't know
if it is possible."

Do you mean only the logical constants top and bottom or also the
connectives?

This would mean mixing up layers... but in the end, in spite of all out
efforts, the layer separation is still causing problems :(

**Comment by gebner** [comment] 2015-05-29 20:01
Fixed by merging the regular layers branch.

**Closed by gebner** 2015-05-29 20:01 UTC
