### ISSUE TITLE
Reductive cut-elimination loops on proof for a pigeonhole principle formula¬(∀x x = c0 ∧ ∃x f0(x) != f1(x))

### ISSUE THREAD

**Issue by quicquid** [gapt/gapt#684] opened 2018-02-06 18:38 UTC
Please consider the following code:

    val f = hof"¬(∀x x = c0 ∧ ∃x f0(x) != f1(x))"
    val Some(p) = EProver.getLKProof(f)
    ReductiveCutElimination(p)
    // seems not to terminate (tried 5 mins)

I am on master at commit a135c927084f14ac3267c4c110c8f9f6c7364419 - can you reproduce this?

**Comment by gebner** [comment] 2018-02-07 12:14
Thank you for this bug report!

After preliminary investigation, I believe this is caused by a fatal design decision in reductive cut-elimination: namely, there are two separate functions:
 1. `reduction: LKProof => Option[( LKProof, SequentConnector )]` that reduces a cut by one step (or returns None if it can't reduce)
 1. `terminateReduction: LKProof => Boolean` which returns true if cut-reduction should terminate.

Clearly this design is a loaded footgun: if `terminateReduction` returns false even though `reduction` can no longer reduce, then we observe nontermination.  This is exactly what happens in your example: there is a cut on an equation that we can't reduce, but terminateReduction checks whether there are any cuts at all.

I think the `terminateReduction` function should be removed.  I'll bring this topic up in today's GAPT meeting, which will start in a few minutes.

**Comment by quicquid** [comment] 2018-02-07 12:17
Thanks for the confirmation and all the best for the meeting :-) Just wanted to remark that it's not time critical for me - I was just checking some input files I generated and wanted to look at the proofs.

**Comment by gebner** [comment] 2018-02-07 17:32
@loewenheim @shetzl @Ermine516 Since I wasn't convincing enough at the GAPT meeting, I have created a branch with the obvious fix: just remove the termination predicates altogether.  Removing the predicates not only works *without any other changes whatsoever*, it also fixes this issue.

As requested by @loewenheim, I will post my proposal for the new reductive cut-elimination architecture tomorrow.

**Comment by gebner** [comment] 2018-02-09 15:46
## Proposed solutions

As requested by and discussed with @loewenheim.

@jannikvierling Stefan wants *you* to fix this issue.  Please don't feel pressured to use one of the approaches below.  We can discuss this at the next GAPT meeting or in person.

### Desiderata

 - Cut-reduction should be terminating.
 - It should not fail (or loop) in the presence of rules that can prevent cut-elimination:
   - Theory axioms
   - Induction inferences
   - Definition rules
   - Skolem inferences
   - Equational rules
  - It should be easy-ish to implement different strategies, or do partial cut-elimination:
    - Uppermost first
    - Maximum grade first
    - Do not reduce propositional cuts
    - Reduce to ACNFtop
  - Performance should be better than it is now

The last point is probably hard not to achieve.

### Minimum viable product

Even if our grand plans turn out to be infeasible, I think we can clean up the current code enough to fix this issue in a clean way.  We define a reduction rule to be a function `LKProof => Option[LKProof]`[1], the result can be a proof of a subsequent of the original proof.  A basic reduction rule (like grade or rank reduction) is supposed to do a single rewrite step at the last inference of the proof (typically if it is a cut).

```scala
trait Red {
  def apply(p: LKProof): Option[LKProof]

  def orElse(that: Red): Red = ???
  def andThen(that: Red): Red = ???
  
  def run(p: LKProof): LKProof = apply(p).getOrElse(p)
}
object Red {
  def check(p: LKProof => Boolean): Red = ???
}

// goes recursively through the proof and applies `red` to the result
// if `red` can reduce, then uppermostFirst calls itself recursively again
// -> implements uppermost-first reduction strategy
def uppermostFirst(red: Red): Red = ???

object gradeReduction extends Red
object leftRankReduction extends Red // should probably not commute cuts by default
// ...
  
def reductiveCutElimination(p: LKProof): LKProof =
  uppermostFirst(Red.check(isTopmostCut) andThen 
    (gradeReduction orElse leftRankReduction orElse rightRankReduction)).run(p)
```

The reductions `gradeReduction`, `leftRankReduction` would be implemented exactly as they are now. 
Also the check for top-most cut is present at the moment.  The only algorithmic change is that we remove the termination predicate (which fixes this issue, as shown in the linked PR).

See also [Paulson 1983] for a similar approach to rewriting in LCF.

### A bit of fun: monads

The `Red` type outlined in the previous section clearly generalizes to a monad:
```scala
trait Red[+T] {
  def apply(p: LKProof): Option[(LKProof, T)]

  def orElse[S >: T](that: Red[S]): Red[S] = ???
  def flatMap[U](f: T => Red[U]): Red[U] = ???
  def andThen[U](that: Red[U]): Red[U] = flatMap(_ => that)

  def run(p: LKProof): LKProof = apply(p).map(_._1).getOrElse(p)
}
object Red {
  def pure[T](t: T): Red[T] = p => Some(p, t)
}

// goes recursively through the proof and applies `red` to the result
// if `red` can reduce, then uppermostFirst calls itself recursively again
// -> implements uppermost-first reduction strategy
def uppermostFirst(red: Red[Any]): Red[Unit] = ???

object gradeReduction extends Red[Unit]
object leftRankReduction extends Red[Unit]
// ...
```

@loewenheim asked me: why?  Aside from the obvious answer---because we can!---the monadic approach has very nice applications, e.g. restricting grade reduction to quantified cuts:
```scala
val here: Red[LKProof] = p => Some(p, p)
  
val quantifiedGradeReduction: Red[Unit] =
  for {
    c @ CutRule(_, _, _, _) <- here
    if containsQuantifierOnLogicalLevel(c.cutFormula)
    _ <- gradeReduction
  } yield ()
```

### Further extensions

We can define a `maximumGradeFirst(red: Red[Any]): Red[Unit]` combinator that searches for the uppermost cut with maximum grade, then applies `red` there and repeats until finished.  (I don't see any way to do this without looking every time at the whole proof.  Needs to commute cuts.)

Maybe we can remove the `isTopmostCut` check as well.  I believe that uppermost-first alone should be enough to guarantee termination, as long as we don't commute cuts.

Not reducing propositional cuts: here we need to rank reduce cuts (i.e., commute cuts).  For termination reasons, we should only move quantified cuts above propositional cuts though.  This just requires `rankReduceCuts: Red[Unit]` plus `quantifiedGradeReduction` as defined above.

ACNFtop: similar to how it works now.  I believe we can drop the `isACNFtop` check on non-atomic cuts similar to the quantified cut reduction.  Atomic cuts retain their current check.

## Footnotes

[1] I'm a bit on the fence on whether we should use SequentConnectors or not.  Right now, it's a sham because we just guess them after grade and rank reduction.  However @shetzl made the point that tracking formula ancestorship correctly is of significant importance---if we ignore ancestorship, then we get many more cut-elimination normal forms for some proofs.  In any case, I'm ignoring sequent connectors here for ease of exposition.

[Paulson 1983] Larry Paulson, A higher-order implementation of rewriting, 1983.  http://www.cl.cam.ac.uk/~lp15/papers/Reports/TR035-lcp-rewriting.pdf

**Comment by jannikvierling** [comment] 2018-02-10 08:05
I don't quite understand the scope of the issue and the proposed changes. Is this about fixing the non-termination bug or about implementing a new architecture for reductive cut-elimination? In the latter case I would like to collect further requirements so that we may come up with a solid architecture that satisfies our needs for the foreseeable future. We may for example also want to use an architecture that can parallelize some parts of the rewriting process.

**Comment by gebner** [comment] 2018-02-10 08:45
I now realize that this must come a bit out of nowhere for you since you weren't here on Wednesday.  We (@shetzl, @loewenheim, and me) were talking about the non-termination bug, I mentioned a possible refactoring and @loewenheim asked me to elaborate on it by writing up a concrete proposal here.  Then @loewenheim asked me about a monadic version yesterday, and that's why I wrote that section.

From my point of view, the pressing objectives are:
 1. Fix the non-termination bug, and get rid of the termination predicates.
 2. Improve performance.  (Not long ago, a paper appeared that benchmarked the reductive cut-elimination implementation in GAPT, and concluded that reductive cut-elimination is slow in general.  This feels a bit like benchmarking a resolution prover without term ordering or subsumption, and concluding that heuristic instantiation by random terms is the practically efficient alternative.  People expect GAPT to be fast, and we should not undermine their trust.)

To clarify, I did not expect you to implement any of the proposals.  I also agree that it is a good idea to gather more requirements for a new cut-reduction architecture.

**Comment by gebner** [comment] 2018-02-23 16:33
@jannikvierling The non-termination bug here should be fixed in one way or another.  Please choose whatever solution you like best.  (I already proposed [a fix here](https://github.com/gapt/gapt/commit/f95fc472eb05391929285e4ee4261abdbdee6c8c).)

**Closed** 2018-02-24 07:38 UTC
Labels: Bug 🐛
