### ISSUE TITLE
definition elimination fails on lattice proof

### ISSUE THREAD

**Issue by newca12** [gapt/gapt#274] opened 2015-01-27 12:34 UTC
_From [stefan.hetzl](https://code.google.com/u/stefan.hetzl/) on November 03, 2014 14:52:24_

I am currently trying to have a closer look at the lattice proof using gapt (for purposes of cut-introduction) but stumbled over the following problem:

1) Start ./gui.sh
2) Open examples/lattice/lattice.xml.gz
3) Click on "LK Proof -> Eliminate Definitions"

This results in:
LKUnaryRuleCreationException: "Formulas to be contracted are not identical"

It should result in a proof without definitions.

_Original issue: http://code.google.com/p/gapt/issues/detail?id=274_

**Comment by shetzl** [comment] 2015-02-02 09:56
adding CCs from google code: @shetzl @frehn @quicquid

**Comment by frehn** [comment] 2015-02-09 11:30
I'll take a look at that. For reference, to reproduce in CLI, do

import at.logic.algorithms.rewriting.DefinitionElimination

val db = loadProofDB("examples/lattice/lattice.xml.gz")
val defmap = db.Definitions
val proof = db.proofs.head._2
DefinitionElimination(defmap, proof)

**Comment by quicquid** [comment] 2015-02-09 13:47
Hi Daniel!

The reason is that these are defintions from an hlk input, which we
cannot eliminate at the moment. The format of eliminate definitions is a
table with entries like D(x,y) -> (x<y) \lor (x=y) where the free
variables on both sides are identical and the left hand side is atomic.
The format in hlk is different, see for instance the line

define infix predicate \leq by (x \cap y) = x ;

in the first theory block of lattice.hlk [1], where the order of
parameters is implicit. I never found semantics for these parts of hlk
(also for recursive definitions etc.), so I did not take them into
account. With according knowledge, it should be easy to expand the hlk
definitions into the implemented ones.

with kind regards, Martin


[1] http://www.logic.at/ceres/examples/lattice/lattice.hlk

**Comment by frehn** [comment] 2015-02-09 16:01
Hi Martin,

the HLK example you quote is simply to be interpreted as

\leq(x,y) -> (x \cap y) = x;

where there is some implicit order imposed on the variables on the right (I don't know exactly which) determining their order on the left.

This seems to be implemented in GAPT already, since the lattice proof imports fine now on 592ae7c2b3353521a81b7786a1d72fd337d438ed.

Stefan, could you please check whether this fixes the original bug?

**Comment by shetzl** [comment] 2015-02-09 16:13
Thanks for the fix Daniel! I confirm that the elimination of definitions from the lattice proof (as described above) works now. Therefore I am closing this issue.

If I remember correctly the HLK-convention for variables is: the 1st on the left is the 1st on the right, the 2nd on the left is the second on the right etc. HLK also allowed to give variable names explicitely like in \leq(x,y) -> (y \cap x) = x;

**Closed by shetzl** 2015-02-09 16:13 UTC
Labels: Bug, High Priority, Imported
