### ISSUE TITLE
prooftool: wobbling

### ISSUE THREAD

**Issue by gebner** [gapt/gapt#545] opened 2016-07-18 15:23 UTC
When drawing sequent proofs, we have a cyclic dependency in the layout: the length of the inference line is determined based on the size of the subproofs, which then changes the layout of the subproofs, which then changes the length of the inference line...

At least I think that's what's happening.  For a demo, run the following:
```scala
prooftool(LinearExampleProof(20))
```

**Comment by quicquid** [comment] 2016-07-18 15:47
I just ran the example on my computer and it seems the left end of the sequent is not correctly computed - is this a consequence of your change or unrelated?

![pt-bug1](https://cloud.githubusercontent.com/assets/436903/16920825/8275c6c0-4d0f-11e6-9f18-81afc5eb8c2b.png)

**Comment by gebner** [comment] 2016-07-18 15:57
This is #547, it was introduced in the `prooftool-wip` branch by the refactoring of `DrawSequentProof` into separate panels for the inference line and the subproofs.

**Comment by shetzl** [comment] 2016-09-23 15:24
In my opinion, this should also be fixed before the 2.3 release.

**Comment by shetzl** [comment] 2016-10-07 15:31
I cannot reproduce this with current master.

@loewenheim: If I remember correctly, you said last week that this is fixed.

Can we consider this issue closed?

**Comment by loewenheim** [comment] 2016-10-07 15:37
@shetzl With the current master, `LinearExampleProof(20)` looks really strange, because I made a logical error regarding end sequent alignment. I'm in the process of fixing it, but right now the proof is wobbling on my end. I wouldn't close this quite yet.

**Comment by loewenheim** [comment] 2016-10-07 16:22
As of 4afd48175324bfc17f0c14bc720a6446b26312e2, it's not wobbling any more for me. Is it still happening for anyone else?

**Comment by quicquid** [comment] 2016-10-09 18:48
On my computer, there's a very fast animation-like buildup but feels more like growing than wobbling anymore.

**Closed** 2016-10-10 12:21 UTC
Labels: Bug, prooftool
